
project_id = "sfbohkqmykagkdmggcxw"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]
enabled = true
port = 54322
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://localhost:3000"]

[auth.email]
enable_signup = true
enable_confirmations = false

[db]
port = 54323

[studio]
enabled = true
port = 54324

[inbucket]
enabled = true
port = 54325

[storage]
enabled = true
port = 54326

[edge_functions]
enabled = true
port = 54327

[analytics]
enabled = false

[functions.crawl-manager]
verify_jwt = false

[functions.enhanced-disaster-sync]
verify_jwt = false

[functions.disasterassist-sync]
verify_jwt = false

[functions.live-disaster-check]
verify_jwt = false

[functions.state-declarations-sync]
verify_jwt = false
